#define OBJECT "/std/Object"
#define AUTOLOAD "/std/autoload"
#define LIVING "/std/living"
#define MONSTER "/std/monster"
#define CONTAINER "/std/container"
#define VOID "/d/standard/void"
#define ROOM "/std/room"
#define DAEMON "/std/daemon"
#define BODY "/std/living/body"
#define SKILLS "/std/living/skills"
#define LOCKER "/std/locker"
#define LOCKER_ROOM "/std/locker_room"
#define VAULT "/std/vault"
#define WEAPON "/std/weapon"
#define ARMOUR "/std/armour"
#define BAG "/std/bag_logic"
#define BARKEEP "/std/barkeep"
#define BBOARD "/std/bboard"
#define MOVE "/std/move"
#define SHADOW "/std/spells/shadows/shadow"
#define PDATA_DIR "/save/adm/users"
#define CONNECTION "/adm/obj/login"
#define DAMAGE_TYPES ({ "crushing", "cutting", "impaling", "fire", "impact", "electricity", "acid", "plasma","vacuum", "cold", "depression", "time", "disruption", "holy","aether", "stress", "strike", "infernal" })
#define DEFAULT_MSG "You do not notice that here.\n"